# Generated by Django 6.0 on 2026-01-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='student_card',
            field=models.ImageField(blank=True, null=True, upload_to='student_cards/'),
        ),
    ]
