# Generated by Django 6.0 on 2026-01-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_membership_student_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='active',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
